version: "3.9"

services:
    postgres:
        image: postgres:alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=user
            - POSTGRES_DB=blog_next
